// Mocks generated by Mockito 5.4.4 from annotations
// in beritapps/test/feature/home/data/repositories/home_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:beritapps/core/models/base_list_resp.dart' as _i2;
import 'package:beritapps/core/network/network_info.dart' as _i6;
import 'package:beritapps/feature/home/data/datasource/home_remote_data_source.dart'
    as _i3;
import 'package:beritapps/feature/home/data/model/article_model.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeBaseListResp_0<T> extends _i1.SmartFake
    implements _i2.BaseListResp<T> {
  _FakeBaseListResp_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HomeRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRemoteDataSource extends _i1.Mock
    implements _i3.HomeRemoteDataSource {
  MockHomeRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.BaseListResp<_i5.ArticleModel>> getTopHeadlinesNews({
    String? countryCode = r'id',
    String? category,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getTopHeadlinesNews,
          [],
          {
            #countryCode: countryCode,
            #category: category,
          },
        ),
        returnValue: _i4.Future<_i2.BaseListResp<_i5.ArticleModel>>.value(
            _FakeBaseListResp_0<_i5.ArticleModel>(
          this,
          Invocation.method(
            #getTopHeadlinesNews,
            [],
            {
              #countryCode: countryCode,
              #category: category,
            },
          ),
        )),
      ) as _i4.Future<_i2.BaseListResp<_i5.ArticleModel>>);
}

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i6.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i4.Future<bool>.value(false),
      ) as _i4.Future<bool>);
}
